Initial commit
teamclairvoyant/airflow-maintenance-dags pull request #126
Opened 2022-07-19 22:44 UTC by nikhilmn

First commit.

2022-08-09 19:14 UTC, prakshalj0512 requested changes
great job on the code! here are a few general suggestions in addition to inline comments:

- [ ] rename PR title to be more relevant
- [ ] remove any & every unused line of code
- [ ] create functions for each different metric and return df & recommendation for use later
- [ ] print out the returned output of each func in the script so it shows up in airflow task logs
- [ ] add docstrings to those functions 
- [ ] Create global variables for things like email list. Check out existing DAGs for reference. 
- [ ] create a func for concatenating multiple strings/df cols
- [ ] parameterize the days (1,3,7)
- [ ] add checks for no data  
- [ ] add if/else clause for _data in serializedDAG

2022-08-09 19:14 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +from yaml import serialize
remove all unused packages

2022-08-09 19:14 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +slamiss = session.query(
remove all references to SlaMiss table

2022-08-09 19:14 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +# print(dagrun_df[:10])
remove all unnecessary code comments

2022-08-09 19:14 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +time_diff_7days = timedelta(days=7, hours=0, minutes=0)
reuse the vars from earlier

```
time_diff_one_week = timedelta(days=7, hours=0, minutes=0)
time_diff_one_day = timedelta(days=7, hours=0, minutes=0)
time_diff_7days = timedelta(days=7, hours=0, minutes=0)
```

2022-08-09 19:14 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +serializeddag = session.query(SerializedDagModel._data).all()
change the `_data` to `data` and see if it works. _data failed to work in v2.2.0.

2022-08-09 19:14 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +df2 = serializeddag_dfjson["_data"].apply(json.dumps)
rename df to something meaningful

2022-08-09 19:14 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +df4 = pd.DataFrame(df3.values.tolist())["dag"]
try to see if you can consolidate all these transformations (line 71-74) into one line

2022-08-09 19:59 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +        subject="Airflow SLA Metrics Report - 08/04/2022",
generate date dynamically

2022-08-09 20:01 UTC, prakshalj0512 commented on sla-miss-report/sla_miss_report.py
> +time_diff_one_day = timedelta(days=7, hours=0, minutes=0)
revert back to 1 day

2022-08-12 19:11 UTC, prakshalj0512 commented
- [ ] Remove methods that cant be reused
- [ ] Rename any DF vars to have either _dag_, _daily_, _hourly
- [ ] Remove hardcoded 1,3,7 days
- [ ] Loop thru the days list wherever it’s being used; try
- [ ] Rename df2-4
- [ ] Try to see if ‘yesterday’ can be used instead of today min time
- [ ] Func for obs5_sladpercent_weekprior, obs5_sladpercent_weekprior
- [ ] Reword the descriptions to be more direct & authorotative
- [ ] Test returning empty DF to jinja templating; adding a check for DF len in templating
- [ ] Format the code before pushing
- [ ] Remove all unused code (SLAMiss table)
- [ ] Create vars for list of days
```
short_time_frame = 1
medium_time_frame = 3
long_time_frame = 7

list_days = [short_time_frame, medium_time_frame, long_time_frame]
```

2022-09-07 17:44 UTC, prakshalj0512 requested changes
Please review the comments. Reference for common issues:
https://clairvoyant.atlassian.net/wiki/spaces/INSIGHT/pages/2749071361/Git+Peer+Reviews

2022-09-14 18:50 UTC, nikhilmn commented on sla-miss-report/sla_miss_report.py
> +        serializeddag_json = serializeddag_df["_data"].apply(json.dumps).apply(json.loads)
resolved

2022-10-24 19:33 UTC, prakshalj0512 approved these changes

2022-10-24 19:34 UTC, merged